name: 'walle'
version: '0.1.0'
author: 'Jake Ob <iakopap@gmail.com>'
homepage: 'https://github.com/tzeikob/walle'
description: 'An opinionated tool to manage and configure conky for developers'
dependencies:
  system:
    - 'python3'
    - 'python3-pip'
    - 'python3-dev'
    - 'iproute2'
    - 'libcairo2-dev'
    - 'pkg-config'
  python:
    - 'ruamel.yaml'
    - 'psutil'
    - 'gputil'
    - 'screeninfo'
    - 'pynput'
    - 'pycairo'
builds:
  debian:
    arch: 'all'