#!/usr/bin/env bash
# A script to be ran after remove

set -e

PKG_NAME="#PKG_NAME"
HOME_DIR=/home/$SUDO_USER
CONFIG_DIR=$HOME_DIR/.config/$PKG_NAME
AUTOSTART_DIR=$HOME_DIR/.config/autostart

echo -e "Startig post remove script"

rm -f /usr/bin/$PKG_NAME
rm -rf /usr/share/$PKG_NAME

echo -e "Installation remnant files have been removed"

# Remove config folder
rm -rf $CONFIG_DIR

echo -e "Config folder has been removed"

# Remove installed font files
rm -rf /usr/local/share/fonts/$PKG_NAME

echo -e "Fonts have been removed"

# Remove autostart desktop file
rm -f $AUTOSTART_DIR/$PKG_NAME.desktop

echo -e "Autostart desktop file has been removed"

echo -e "Exiting post remove script"

exit 0