#!/usr/bin/env bash
# A script to be ran after installation

set -e

PKG_NAME="#PKG_NAME"
INSTALLATION_DIR=/usr/share/$PKG_NAME
HOME_DIR=/home/$SUDO_USER
CONFIG_DIR=$HOME_DIR/.config/$PKG_NAME
AUTOSTART_DIR=$HOME_DIR/.config/autostart
FONTS_DIR=/usr/local/share/fonts/$PKG_NAME

echo -e "Startig post installation script"

# Set the current sudo user to files need user's name
sed -i "s/#USER/$SUDO_USER/g" $INSTALLATION_DIR/lua/main.lua

echo -e "User placeholder values have been injected"

# Create the executable's symbolic link file
ln -s $INSTALLATION_DIR/bin/$PKG_NAME.py /usr/bin/$PKG_NAME

echo -e "Binary symlink file has been created"

# Create config folder
mkdir -p $CONFIG_DIR

# Copy config files to config folder
cp $INSTALLATION_DIR/config.yml $CONFIG_DIR/config.yml
cp $INSTALLATION_DIR/.conkyrc $CONFIG_DIR/.conkyrc

# Copy asset files into the config folder
cp -r $INSTALLATION_DIR/assets $CONFIG_DIR

# Change permissions to sudo user
chown -R $SUDO_USER:$SUDO_USER $CONFIG_DIR

echo -e "Config folder and files have been created"

# Install glyph and alphanumeric fonts
mkdir -p $FONTS_DIR
cp $INSTALLATION_DIR/fonts/*.ttf $FONTS_DIR

echo -e "Fonts have been installed successfully"

# Create the autostart gnome desktop file
mkdir -p $AUTOSTART_DIR
DESKTOP_FILE=$AUTOSTART_DIR/$PKG_NAME.desktop

echo "[Desktop Entry]" >> $DESKTOP_FILE
echo "Type=Application" >> $DESKTOP_FILE
echo "Exec=$PKG_NAME start" >> $DESKTOP_FILE
echo "Hidden=false" >> $DESKTOP_FILE
echo "NoDisplay=false" >> $DESKTOP_FILE
echo "Name[en_US]=$PKG_NAME" >> $DESKTOP_FILE
echo "Name=$PKG_NAME" >> $DESKTOP_FILE
echo "Comment[en_US]=$PKG_NAME Start Up" >> $DESKTOP_FILE
echo "Comment=$PKG_NAME Start Up" >> $DESKTOP_FILE

# Change permissions to sudo user
chown $SUDO_USER:$SUDO_USER $DESKTOP_FILE

echo -e "Autostart desktop file created at '$DESKTOP_FILE'"

echo -e "Exiting post installation script"

exit 0