#!/usr/bin/env bash
# A script to be ran before remove

set -e

PKG_NAME="#PKG_NAME"

echo -e "Starting pre remove script"

echo -e "Trying to stop the process..."

su $SUDO_USER -c "$PKG_NAME stop"

echo -e "Process is down"

echo -e "Exiting pre remove script"

exit 0