version: '#PKG_VERSION'
system:
  monitor: 0
  debug: disabled
theme:
  mode: light
  wallpaper: 0
  lines:
    - font : ''
      text: '${time %H:%M}'
    - font: ''
      text: '$_day_name $_month_name ${time %e, %Y}'
    - font: ''
      text: 'Logged as $user_names at $nodename'
    - font: ''
      text: 'Running $_rls_arch on $_rls_name $_rls_codename'
    - font: ''
      text: 'CPU $cpu% Mem $memperc% Disk ${fs_used_perc /}%'
    - font: ''
      text: 'Up ${upspeedf $_net_name}KiB Down ${downspeedf $_net_name}KiB'
    - font: ''
      text: 'Connected to $_net_name with $_net_ip'
    - font: ''
      text: 'So far $uptime_short uptime!'